modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="lightningfe"
version="${file.jarVersion}"
displayName="LightningFE"
authors="Eolas-Ur"
description='''
LightningFE augments the vanilla Lightning Rod.
When struck by lightning, the rod emits a single-tick burst of 20,000,000 FE into adjacent blocks.
No storage. No buffering. Excess energy is discarded.
Compatible with any mod using NeoForge Energy capability.
'''

[[dependencies.lightningfe]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lightningfe]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"